name: pyarch-ci

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync

      - name: linter
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: run tests
        run: uv run pytest

      - name: type check
        run: uv run mypy src tests

      - name: build package
        run: uv build
